# -*- coding: utf-8 -*-
"""Day 14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzLyLVsMazC0VfjuVmwoRmqmsjw3XHGi
"""

{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# **Day 14**"
      ],
      "metadata": {
        "id": "FjNyGq-5h1K0"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Part 1\n",
        "# Constants for the grid dimensions\n",
        "grid_width = 101\n",
        "grid_height = 103\n",
        "time_limit = 100\n",
        "\n",
        "# Function to determine the quadrant of a robot based on its position\n",
        "def get_quadrant(x, y):\n",
        "    if x == grid_width // 2 or y == grid_height // 2:\n",
        "        return None  # On the middle line, not in any quadrant\n",
        "    elif x < grid_width // 2 and y < grid_height // 2:\n",
        "        return 1  # Top-left quadrant\n",
        "    elif x >= grid_width // 2 and y < grid_height // 2:\n",
        "        return 2  # Top-right quadrant\n",
        "    elif x < grid_width // 2 and y >= grid_height // 2:\n",
        "        return 3  # Bottom-left quadrant\n",
        "    elif x >= grid_width // 2 and y >= grid_height // 2:\n",
        "        return 4  # Bottom-right quadrant\n",
        "\n",
        "# Read input from the file\n",
        "def read_input(file_path):\n",
        "    robots = []\n",
        "    with open(/content/input14part1.txt, 'r') as file:\n",
        "        for line in file:\n",
        "            line = line.strip()\n",
        "            if line:\n",
        "                pos_part, vel_part = line.split()\n",
        "                px, py = map(int, pos_part[2:].split(','))\n",
        "                vx, vy = map(int, vel_part[2:].split(','))\n",
        "                robots.append(((px, py), (vx, vy)))\n",
        "    return robots\n",
        "\n",
        "# Simulate the motion of robots and calculate the safety factor\n",
        "def calculate_safety_factor(robots, time_limit):\n",
        "    # Update positions after 100 seconds\n",
        "    for i in range(len(robots)):\n",
        "        (px, py), (vx, vy) = robots[i]\n",
        "        px = (px + vx * time_limit) % grid_width\n",
        "        py = (py + vy * time_limit) % grid_height\n",
        "        robots[i] = ((px, py), (vx, vy))\n",
        "\n",
        "    # Count robots in each quadrant\n",
        "    quadrant_counts = {1: 0, 2: 0, 3: 0, 4: 0}\n",
        "    for (px, py), _ in robots:\n",
        "        quadrant = get_quadrant(px, py)\n",
        "        if quadrant:\n",
        "            quadrant_counts[quadrant] += 1\n",
        "\n",
        "    # Calculate the safety factor\n",
        "    safety_factor = (quadrant_counts[1] * quadrant_counts[2] *\n",
        "                     quadrant_counts[3] * quadrant_counts[4])\n",
        "    return safety_factor\n",
        "\n",
        "# Main function\n",
        "def main():\n",
        "    input_file = \"input.txt\"\n",
        "    robots = read_input(input_file)\n",
        "    safety_factor = calculate_safety_factor(robots, time_limit)\n",
        "    print(\"Safety Factor:\", safety_factor)\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "fG87C9-sihNT",
        "outputId": "837fdcc9-c747-4c1d-d1b6-1bf6ac1c7802"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Safety Factor: 217132650\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Part 2\n",
        "import numpy as np\n",
        "from typing import List, Tuple\n",
        "\n",
        "def parse_input(filename: str) -> List[Tuple[Tuple[int, int], Tuple[int, int]]]:\n",
        "    \"\"\"\n",
        "    Parse input file to extract robot positions and velocities.\n",
        "\n",
        "    Args:\n",
        "        filename (str): Path to input file\n",
        "\n",
        "    Returns:\n",
        "        List of tuples, each containing (position, velocity)\n",
        "    \"\"\"\n",
        "    robots = []\n",
        "    with open(filename, 'r') as f:\n",
        "        for line in f:\n",
        "            pos_str, vel_str = line.strip().split(' ')\n",
        "            px, py = map(int, pos_str[2:].split(','))\n",
        "            vx, vy = map(int, vel_str[2:].split(','))\n",
        "            robots.append(((px, py), (vx, vy)))\n",
        "    return robots\n",
        "\n",
        "def simulate_robots(robots: List[Tuple[Tuple[int, int], Tuple[int, int]]],\n",
        "                    time: int,\n",
        "                    width: int,\n",
        "                    height: int) -> np.ndarray:\n",
        "    \"\"\"\n",
        "    Simulate robot movements and count robot positions after given time.\n",
        "\n",
        "    Args:\n",
        "        robots (List): List of robot (position, velocity) tuples\n",
        "        time (int): Seconds to simulate\n",
        "        width (int): Space width\n",
        "        height (int): Space height\n",
        "\n",
        "    Returns:\n",
        "        numpy array of robot count per tile\n",
        "    \"\"\"\n",
        "    # Initialize grid to track robot positions\n",
        "    grid = np.zeros((height, width), dtype=int)\n",
        "\n",
        "    for (px, py), (vx, vy) in robots:\n",
        "        # Calculate final position after time, with wraparound\n",
        "        final_x = (px + vx * time) % width\n",
        "        final_y = (py + vy * time) % height\n",
        "        grid[final_y, final_x] += 1\n",
        "\n",
        "    return grid\n",
        "\n",
        "def is_christmas_tree(grid: np.ndarray) -> bool:\n",
        "    \"\"\"\n",
        "    Check if the robot positions form a Christmas tree pattern.\n",
        "\n",
        "    Args:\n",
        "        grid (numpy array): Robot position grid\n",
        "\n",
        "    Returns:\n",
        "        Boolean indicating if a Christmas tree pattern is found\n",
        "    \"\"\"\n",
        "    # Define a potential Christmas tree pattern\n",
        "    # This is a simplistic representation and might need adjustment\n",
        "    # based on the actual expected pattern\n",
        "    tree_pattern = [\n",
        "        [0, 0, 1, 0, 0],   # top of tree\n",
        "        [0, 1, 1, 1, 0],   # middle of tree\n",
        "        [1, 1, 1, 1, 1],   # base of tree\n",
        "    ]\n",
        "\n",
        "    height, width = grid.shape\n",
        "\n",
        "    # Search for the pattern in the grid\n",
        "    for y in range(height - len(tree_pattern)):\n",
        "        for x in range(width - len(tree_pattern[0])):\n",
        "            # Check if this section matches the tree pattern\n",
        "            match = True\n",
        "            for dy, row in enumerate(tree_pattern):\n",
        "                for dx, val in enumerate(row):\n",
        "                    if val == 1 and grid[y+dy, x+dx] == 0:\n",
        "                        match = False\n",
        "                        break\n",
        "                if not match:\n",
        "                    break\n",
        "\n",
        "            if match:\n",
        "                return True\n",
        "\n",
        "    return False\n",
        "\n",
        "def find_christmas_tree_time(filename: str, max_time: int = 10000, width: int = 101, height: int = 103) -> int:\n",
        "    \"\"\"\n",
        "    Find the earliest time when robots form a Christmas tree pattern.\n",
        "\n",
        "    Args:\n",
        "        filename (str): Input file path\n",
        "        max_time (int): Maximum time to search\n",
        "        width (int): Space width\n",
        "        height (int): Space height\n",
        "\n",
        "    Returns:\n",
        "        Time when Christmas tree pattern is found, or -1 if not found\n",
        "    \"\"\"\n",
        "    # Parse input\n",
        "    robots = parse_input(filename)\n",
        "\n",
        "    # Search for Christmas tree pattern\n",
        "    for time in range(max_time):\n",
        "        # Simulate robot positions\n",
        "        grid = simulate_robots(robots, time, width, height)\n",
        "\n",
        "        # Check for Christmas tree pattern\n",
        "        if is_christmas_tree(grid):\n",
        "            return time\n",
        "\n",
        "    return -1  # No pattern found within max_time\n",
        "\n",
        "# Solve problem\n",
        "result = find_christmas_tree_time('input.txt')\n",
        "print(f\"Seconds until Christmas Tree Pattern: {result}\")\n"
      ],
      "metadata": {
        "id": "4KLAg0Rcmu9-"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}

# Part 1: Safety Factor Calculation

# Constants for the grid dimensions
grid_width = 101
grid_height = 103
time_limit = 100

# Function to determine the quadrant of a robot based on its position
def get_quadrant(x, y):
    if x == grid_width // 2 or y == grid_height // 2:
        return None  # On the middle line, not in any quadrant
    elif x < grid_width // 2 and y < grid_height // 2:
        return 1  # Top-left quadrant
    elif x >= grid_width // 2 and y < grid_height // 2:
        return 2  # Top-right quadrant
    elif x < grid_width // 2 and y >= grid_height // 2:
        return 3  # Bottom-left quadrant
    elif x >= grid_width // 2 and y >= grid_height // 2:
        return 4  # Bottom-right quadrant

# Read input from the file
def read_input(file_path):
    robots = []
    with open(file_path, 'r') as file:
        for line in file:
            line = line.strip()
            if line:
                pos_part, vel_part = line.split()
                px, py = map(int, pos_part[2:].split(','))
                vx, vy = map(int, vel_part[2:].split(','))
                robots.append(((px, py), (vx, vy)))
    return robots

# Simulate the motion of robots and calculate the safety factor
def calculate_safety_factor(robots, time_limit):
    # Update positions after time_limit seconds
    for i in range(len(robots)):
        (px, py), (vx, vy) = robots[i]
        px = (px + vx * time_limit) % grid_width
        py = (py + vy * time_limit) % grid_height
        robots[i] = ((px, py), (vx, vy))

    # Count robots in each quadrant
    quadrant_counts = {1: 0, 2: 0, 3: 0, 4: 0}
    for (px, py), _ in robots:
        quadrant = get_quadrant(px, py)
        if quadrant:
            quadrant_counts[quadrant] += 1

    # Calculate the safety factor
    safety_factor = (quadrant_counts[1] * quadrant_counts[2] *
                     quadrant_counts[3] * quadrant_counts[4])
    return safety_factor

# Main function for Part 1
def part1():
    input_file = "input14part1.txt"
    robots = read_input(input_file)
    safety_factor = calculate_safety_factor(robots, time_limit)
    print("Safety Factor:", safety_factor)

# Part 2: Christmas Tree Detection
import numpy as np
from typing import List, Tuple

# Parse input file to extract robot positions and velocities
def parse_input(filename: str) -> List[Tuple[Tuple[int, int], Tuple[int, int]]]:
    robots = []
    with open(filename, 'r') as f:
        for line in f:
            pos_str, vel_str = line.strip().split(' ')
            px, py = map(int, pos_str[2:].split(','))
            vx, vy = map(int, vel_str[2:].split(','))
            robots.append(((px, py), (vx, vy)))
    return robots

# Simulate robot movements and count robot positions after given time
def simulate_robots(robots: List[Tuple[Tuple[int, int], Tuple[int, int]]],
                    time: int, width: int, height: int) -> np.ndarray:
    grid = np.zeros((height, width), dtype=int)
    for (px, py), (vx, vy) in robots:
        final_x = (px + vx * time) % width
        final_y = (py + vy * time) % height
        grid[final_y, final_x] += 1
    return grid

# Check if the robot positions form a Christmas tree pattern
def is_christmas_tree(grid: np.ndarray) -> bool:
    tree_pattern = [
        [0, 0, 1, 0, 0],   # top of tree
        [0, 1, 1, 1, 0],   # middle of tree
        [1, 1, 1, 1, 1],   # base of tree
    ]
    height, width = grid.shape

    for y in range(height - len(tree_pattern)):
        for x in range(width - len(tree_pattern[0])):
            match = True
            for dy, row in enumerate(tree_pattern):
                for dx, val in enumerate(row):
                    if val == 1 and grid[y+dy, x+dx] == 0:
                        match = False
                        break
                if not match:
                    break
            if match:
                return True
    return False

# Find the earliest time when robots form a Christmas tree pattern
def find_christmas_tree_time(filename: str, max_time: int = 10000, width: int = 101, height: int = 103) -> int:
    robots = parse_input(filename)
    for time in range(max_time):
        grid = simulate_robots(robots, time, width, height)
        if is_christmas_tree(grid):
            return time
    return -1

# Main function for Part 2
def part2():
    input_file = "/content/input14part1.txt"
    time = find_christmas_tree_time(input_file)
    if time != -1:
        print("Christmas Tree formed at time:", time)
    else:
        print("No Christmas Tree pattern found.")

if __name__ == "__main__":
    part1()
    part2()

