# -*- coding: utf-8 -*-
"""google advent of code day 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VhHSrPNgUV-eo-68dcMKqd50x23Hk0TK
"""

def calculate_total_distance_from_file(filename):
    left_list = []
    right_list = []

    # Read the input file and populate the lists
    with open(filename, 'r') as file:
        for line in file:
            left, right = map(int, line.split())
            left_list.append(left)
            right_list.append(right)

    # Sort the lists
    left_list.sort()
    right_list.sort()

    # Calculate the total distance
    total_distance = sum(abs(l - r) for l, r in zip(left_list, right_list))

    return total_distance

# Replace 'input.txt' with the name of your input file
filename = '/content/input.txt'
total_distance = calculate_total_distance_from_file(filename)
print(f"Total distance between the lists: {total_distance}")

from collections import Counter

def calculate_similarity_score(filename):
    left_list = []
    right_list = []

    # Read the input file and populate the lists
    with open(filename, 'r') as file:
        for line in file:
            left, right = map(int, line.split())
            left_list.append(left)
            right_list.append(right)

    # Count occurrences of each number in the right list
    right_count = Counter(right_list)

    # Calculate the similarity score
    similarity_score = sum(num * right_count[num] for num in left_list)

    return similarity_score

# Replace 'input.txt' with the name of your input file
filename = '/content/input2.txt'
similarity_score = calculate_similarity_score(filename)
print(f"Similarity score: {similarity_score}")